### PR TITLE
*: add a global flow-id field as single dataflow identifier

### PR DESCRIPTION
**Pull request by amyangfei**
- A little refactor, add a `flow-id` field to distinguish user submit jobs
- sink output to different dir based on the `flow-id`

### CODE REVIEW

**Comment by hanfei1991** [comment]
Is flow-id to distinguish users?

**Comment by amyangfei** [comment]
> Is flow-id to distinguish users?

not exactly, it acts like `DM task id` or `cdc changefeed name`, maybe we can also add a struct to contain more information of dataflow, such as 
```go
type Auto struct {
    FlowID string
    UserID int64
    // ...
}
```

**Comment by amyangfei** [comment]
I don't know why circleCI is not running.

**Comment by hanfei1991** [comment]
I just set circle ci applied to all forks. I don't know why it doesn't work

**Review by hanfei1991 — APPROVED** [review]

**Pull request merged**
